#!/usr/bin/env bash

usage() {
  echo "Usage: $0 [<input> [<output>]]"
  echo ""
  echo "  <input> can be a file or a directory, default: '/source' directory"
  echo "  <output> should be a file or a directory, default: same directory as <input>"
  echo ""
  echo "  if <input> is a directory"
  echo "  then all *.msg files in it will be processed"
  echo "  and <output> should also be a directory"
  echo "  otherwise <input> should be a msg file"
}

JAVA_OPTS="-Duser.timezone=${DATE_TIMEZONE:-Europe/Brussels} -Duser.language=${DATE_LANGUAGE:-nl} -Duser.country=${DATE_COUNTRY:-BE}"
CMD_OPTS="-d -hd -a"

CMD="java ${JAVA_OPTS} -jar /emailconverter/emailconverter.jar ${CMD_OPTS}"

convert_file() {
  if [ -d "${TARGET}" ]
  then
    file="$(basename -- "$1")"
    tgt="${TARGET}/${file}.pdf"
  else
    tgt="${TARGET}"
    mkdir -p "$(basename -- "${tgt}")"
  fi
  echo "Converting $(basename "$1") to ${tgt} ..."
  ${CMD} -o "${tgt}" "$1"
}

SOURCE="${1:-/source}"

if [ -f "$SOURCE" ]
then
  TARGET="${2:-$(dirname "$SOURCE")}"
  [ -d "$TARGET" ] || { echo -e "ERROR: Directory '$TARGET' does not exist\n"; usage; exit 3; }
  convert_file "$SOURCE"
elif [ -d "$SOURCE" ]
then
  TARGET="${2:-${SOURCE}}"
  [ -d "$TARGET" ] || { echo -e "ERROR: Directory '$TARGET' does not exist\n"; usage; exit 3; }
  for f in $SOURCE/*.msg
  do
    convert_file "$f"
  done
else
  echo -e "ERROR: '$SOURCE' does not exist or is not a directory or file\n"
  usage
  exit 4
fi
